[workspace]
members = [
    "ffxiv/sqpack_reader",
    "ffxiv/ffxiv_parser",
    "ffxiv/model_viewer",
    "server",
    "renderer",
    "util",
]
default-members = ["ffxiv/model_viewer", "server"]

[profile.release]
panic = "abort"
