[workspace]
members = [
    "libs/sqpack_reader",
    "libs/ffxiv_parser",
    "libs/ffxiv_renderer",
    "libs/renderer",
    "libs/util",
    "tools/sqpack_extractor",
    "tools/ffxiv_renderer_standalone",
    "server",
    "apps/model_viewer"
]
default-members = ["tools/sqpack_extractor", "tools/ffxiv_renderer_standalone", "server", "apps/model_viewer"]

[profile.release]
panic = "abort"
lto = true
