[workspace]
members = [
    "libs/sqpack_reader",
    "libs/ffxiv_parser",
    "libs/ffxiv_renderer",
    "libs/renderer",
    "libs/util",
    "tools/sqpack_extractor",
    "tools/ffxiv_renderer_standalone",
    "server",
    "apps/model_viewer",
    "apps/translation_compare"
]

[profile.release]
panic = "abort"
lto = true
