[workspace]
members = [
    "libs/sqpack_reader",
    "libs/ffxiv_parser",
    "libs/ffxiv_renderer",
    "libs/renderer",
    "libs/util",
    "utils/sqpack_extractor",
    "server",
    "apps/model_viewer"
]
default-members = ["utils/sqpack_extractor", "server", "apps/model_viewer"]

[profile.release]
panic = "abort"
lto = true
