[workspace]
members = [
    "ffxiv/sqpack_reader",
    "ffxiv/sqpack_extractor",
    "ffxiv/ffxiv_parser",
    "ffxiv/model_viewer",
    "server",
    "renderer",
    "util",
    "web"
]
default-members = ["ffxiv/model_viewer", "server", "web"]

[profile.release]
panic = "abort"
lto = true
