version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./data:/server/data
    environment:
      ROCKET_PROFILE: release
      ROCKET_ADDRESS: 0.0.0.0
    ports:
      - 8000:8000
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8080:80
