FROM lukemathwalker/cargo-chef:latest-rust-1 AS base
WORKDIR /src

FROM base AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM base AS builder
COPY --from=planner /src/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json --package server

COPY . .
RUN cargo build -p server --release

FROM debian:stretch-slim
COPY --from=builder /src/target/release/server /server/

EXPOSE 8000
WORKDIR "/server"
ENTRYPOINT ["/server/server"]
