#syntax=docker/dockerfile:experimental

FROM dlunch/rust:1.60.0-stretch as builder

WORKDIR /src
COPY . .

RUN --mount=type=cache,target=/src/target cargo install --path server --locked --bins --root build

FROM debian:stretch-slim
COPY --from=builder /src/build/bin /server

EXPOSE 8000
WORKDIR "/server"
ENTRYPOINT ["/server/server"]
