apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffxivtools-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ffxivtools-server
      app.kubernetes.io/name: ffxivtools-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ffxivtools-server
        app.kubernetes.io/name: ffxivtools-server
    spec:
      containers:
        - name: ffxivtools-server
          image: ghcr.io/dlunch/ffxivtools:latest-server
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /server/data
          livenessProbe:
            httpGet:
              path: /probe
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /parsed/ex/kor_521/classjob
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ffxivtools-data
