apiVersion: v1
kind: Service
metadata:
  name: ffxivtools-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ffxivtools-server
    app.kubernetes.io/name: ffxivtools-server
  ports:
  - port: 8000
