[package]
name = "server"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
tokio = { version = "^0.2.11", features = ["macros"], default-features = false }
lazy_static = { version = "^1.4", default-features = false }
actix-web = { version = "^2.0", default-features = false }
actix-rt = { version = "^1.0", default-features = false }
serde_json = {version = "^1.0", default-features = false }
ffxiv_parser = { version = "^0.1", features = ["std"], default-features = false, path = "../ffxiv/ffxiv_parser" }
sqpack_reader = { version = "^0.1", features = ["std"], default-features = false, path = "../ffxiv/sqpack_reader"}
