[package]
name = "server"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "^0.2.11", features = ["macros"], default-features = false }
warp = { version = "^0.2.1", default-features = false }
dotenv = { version = "^0.15", default-features = false }
ffxiv_parser = { version = "^0.1", default-features = false, path = "../ffxiv/ffxiv_parser" }
