[package]
name = "model_viewer_standalone"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[[bin]]
name = "model_viewer_standalone"
path = "src/main.rs"

[features]

[dependencies]
winit = { version = "^0.22", default-features = false }
async-std = { version = "^1.6", features = ["attributes"], default-features = false }
futures = {version = "^0.3", features = ["default"], default-features = false }
nalgebra = { version = "^0.21", default-features = false }
pretty_env_logger = { version = "^0.4", default-features = false }
log = { version = "^0.4", default-features = false }
hashbrown = { version = "^0.7", features = ["ahash", "inline-more"], default-features = false }
once_cell = { version = "^1.4", features = ["std"], default-features = false }

ffxiv_model = { version = "^0.1", default-features = false, path = "../../libs/ffxiv_model" }
sqpack_reader = { version = "^0.1", features = ["std"], default-features = false, path = "../../libs/sqpack_reader" }
renderer = { version = "^0.1", default-features = false, path = "../../libs/renderer" }
