[package]
name = "native"
version = "0.1.0"
authors = ["Inseok Lee <dlunch@gmail.com>"]
edition = "2018"

[lib]
doctest = false
crate-type = ["cdylib"]

[features]
electron = []

[dependencies]
napi = { version = "^0.5" }
napi-derive = { version = "^0.5" }

[build-dependencies]
napi-build = { version = "^0.2" }